server:
  port: 8080

spring:
  application:
    name: techl

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/techl?useUnicode=true&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전

cloud:
  aws:
    s3:
      bucket: techlbucket
    credentials:
      accessKey: AKIAV4TFOZXBDQCAIDR6
      secretKey: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false